# ---
# - name: Converge
#   hosts: all
#   tasks:
#     - name: "Include afreisinger.dotfiles"
#       include_role:
#         name: "afreisinger.dotfiles"

---
- name: Converge
  hosts: all
  #become: true

  pre_tasks:
    - name: Update apt cache.
      apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

  roles:
    - role: afreisinger.git
    - role: afreisinger.dotfiles